Output docs/download.gif

Require canvas-cli

Set Shell fish
Set FontSize 32
Set Width 1500
Set Height 800
Set LoopOffset 50%
Set Framerate 24

Type "canvas-cli download" Sleep 500ms  Enter
Sleep 3s

# select course
Left # fix rendering issue
Sleep 1s
Down
Sleep 1s
Enter
Sleep 1s

# select assignment
Type@200ms "rev" Sleep 2000ms
Space
Sleep 1s
Down@200ms 3
Sleep 1s
Space
Sleep 1s
Enter

Sleep 8s
